// <auto-generated />
using System;
using HousingAllotmentManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HousingAllotmentManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AITStudent")
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Allotment", b =>
                {
                    b.Property<int>("AllotmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllotmentId"));

                    b.Property<DateOnly>("AllotmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("AllotmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AllotmentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Booked");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<decimal>("BookingAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AllotmentId")
                        .HasName("PK__Allotmen__E9FEF60FD165CD91");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("PropertyId");

                    b.HasIndex(new[] { "AllotmentNumber" }, "UQ__Allotmen__F43E412123E3D83C")
                        .IsUnique();

                    b.ToTable("Allotments", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<string>("AmenityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("AmenityId")
                        .HasName("PK__Amenitie__842AF50BF8FBAB69");

                    b.HasIndex(new[] { "AmenityName" }, "UQ__Amenitie__7B4A459F5B470095")
                        .IsUnique();

                    b.ToTable("Amenities", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<decimal?>("AnnualIncome")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomineeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomineeRelation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId")
                        .HasName("PK__Applicat__C93A4C99CA7CB274");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Applications", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("BrowserInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId")
                        .HasName("PK__AuditLog__EB5F6CBDAA30C653");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Emiplan", b =>
                {
                    b.Property<int>("EmiplanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EMIPlanId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmiplanId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("EmiendDate")
                        .HasColumnType("date")
                        .HasColumnName("EMIEndDate");

                    b.Property<DateOnly>("EmistartDate")
                        .HasColumnType("date")
                        .HasColumnName("EMIStartDate");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyEmi")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("MonthlyEMI");

                    b.Property<DateOnly>("NextDueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("OutstandingBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PaidEmis")
                        .HasColumnType("int")
                        .HasColumnName("PaidEMIs");

                    b.Property<string>("PlanStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("RemainingEmis")
                        .HasColumnType("int")
                        .HasColumnName("RemainingEMIs");

                    b.Property<int>("TotalEmis")
                        .HasColumnType("int")
                        .HasColumnName("TotalEMIs");

                    b.HasKey("EmiplanId")
                        .HasName("PK__EMIPlans__201438C967969F60");

                    b.HasIndex("LoanId");

                    b.ToTable("EMIPlans", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.HousingScheme", b =>
                {
                    b.Property<int>("SchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchemeId"));

                    b.Property<string>("BannerImage")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Brochure")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("LastApplicationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LaunchDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("TotalUnits")
                        .HasColumnType("int");

                    b.HasKey("SchemeId")
                        .HasName("PK__HousingS__DB7E1A627551CBA3");

                    b.ToTable("HousingSchemes", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Installment", b =>
                {
                    b.Property<int>("InstallmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstallmentId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("EmiplanId")
                        .HasColumnType("int")
                        .HasColumnName("EMIPlanId");

                    b.Property<decimal>("InstallmentAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("LateFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InstallmentId")
                        .HasName("PK__Installm__42B42D82FDA40456");

                    b.HasIndex("EmiplanId");

                    b.ToTable("Installments", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<int>("AllotmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Emiamount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("EMIAmount");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoanStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Active");

                    b.Property<int>("LoanTenure")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SanctionDate")
                        .HasColumnType("date");

                    b.HasKey("LoanId")
                        .HasName("PK__Loans__4F5AD457605EC373");

                    b.HasIndex("AllotmentId");

                    b.HasIndex(new[] { "LoanNumber" }, "UQ__Loans__EEC26628AAEF7968")
                        .IsUnique();

                    b.ToTable("Loans", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("SentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Sent");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E129114B071");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("InstallmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Success");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A388E5BF6BA");

                    b.HasIndex("InstallmentId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TransactionId" }, "UQ__Payments__55433A6A71835DA9")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.HasIndex(new[] { "ReceiptNumber" }, "UQ__Payments__C08AFDAB7B50AA5D")
                        .IsUnique()
                        .HasFilter("[ReceiptNumber] IS NOT NULL");

                    b.ToTable("Payments", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<decimal?>("BookingAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("BuiltupArea")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("CarpetArea")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facing")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FloorPlanImage")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PlotNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PropertyId")
                        .HasName("PK__Properti__70C9A73536F11736");

                    b.HasIndex("SchemeId");

                    b.ToTable("Properties", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.PropertyAmenity", b =>
                {
                    b.Property<int>("PropertyAmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyAmenityId"));

                    b.Property<int?>("AmenityId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("PropertyAmenityId")
                        .HasName("PK__Property__0D6BB45E11D852F0");

                    b.HasIndex("AmenityId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyAmenities", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A64327652");

                    b.ToTable("Roles", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AadhaarNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("AnnualIncome")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pannumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PANNumber");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C23EDA423");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Mobile" }, "UQ__Users__6FAE0782435CDC2F")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534DE3FB8E8")
                        .IsUnique();

                    b.ToTable("Users", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.UserDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("AadhaarCard")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BankStatement")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IncomeCertificate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OtherDocument")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Pancard")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PANCard");

                    b.Property<string>("PassportPhoto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SalarySlip")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("datetime");

                    b.HasKey("DocumentId")
                        .HasName("PK__UserDocu__1ABEEF0FAE576FBE");

                    b.HasIndex("UserId");

                    b.ToTable("UserDocuments", "AITStudent");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Allotment", b =>
                {
                    b.HasOne("HousingAllotmentManagementSystem.Models.Application", "Application")
                        .WithMany("Allotments")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_Allotments_Applications");

                    b.HasOne("HousingAllotmentManagementSystem.Models.Property", "Property")
                        .WithMany("Allotments")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_Allotments_Properties");

                    b.Navigation("Application");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Application", b =>
                {
                    b.HasOne("HousingAllotmentManagementSystem.Models.Property", "Property")
                        .WithMany("Applications")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_Properties");

                    b.HasOne("HousingAllotmentManagementSystem.Models.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_Users");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.AuditLog", b =>
                {
                    b.HasOne("HousingAllotmentManagementSystem.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AuditLogs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Emiplan", b =>
                {
                    b.HasOne("HousingAllotmentManagementSystem.Models.Loan", "Loan")
                        .WithMany("Emiplans")
                        .HasForeignKey("LoanId")
                        .IsRequired()
                        .HasConstraintName("FK_EMIPlans_Loans");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Installment", b =>
                {
                    b.HasOne("HousingAllotmentManagementSystem.Models.Emiplan", "Emiplan")
                        .WithMany("Installments")
                        .HasForeignKey("EmiplanId")
                        .IsRequired()
                        .HasConstraintName("FK_Installments_EMIPlans");

                    b.Navigation("Emiplan");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Loan", b =>
                {
                    b.HasOne("HousingAllotmentManagementSystem.Models.Allotment", "Allotment")
                        .WithMany("Loans")
                        .HasForeignKey("AllotmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Loans_Allotments");

                    b.Navigation("Allotment");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Notification", b =>
                {
                    b.HasOne("HousingAllotmentManagementSystem.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Payment", b =>
                {
                    b.HasOne("HousingAllotmentManagementSystem.Models.Installment", "Installment")
                        .WithMany("Payments")
                        .HasForeignKey("InstallmentId")
                        .HasConstraintName("FK_Payments_Installments");

                    b.HasOne("HousingAllotmentManagementSystem.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Users");

                    b.Navigation("Installment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Property", b =>
                {
                    b.HasOne("HousingAllotmentManagementSystem.Models.HousingScheme", "Scheme")
                        .WithMany("Properties")
                        .HasForeignKey("SchemeId")
                        .IsRequired()
                        .HasConstraintName("FK__Propertie__Schem__164F3FA9");

                    b.Navigation("Scheme");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.PropertyAmenity", b =>
                {
                    b.HasOne("HousingAllotmentManagementSystem.Models.Amenity", "Amenity")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("AmenityId")
                        .HasConstraintName("FK__PropertyA__Ameni__20CCCE1C");

                    b.HasOne("HousingAllotmentManagementSystem.Models.Property", "Property")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("PropertyId")
                        .HasConstraintName("FK__PropertyA__Prope__1FD8A9E3");

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.User", b =>
                {
                    b.HasOne("HousingAllotmentManagementSystem.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__RoleId__0EAE1DE1");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.UserDocument", b =>
                {
                    b.HasOne("HousingAllotmentManagementSystem.Models.User", "User")
                        .WithMany("UserDocuments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserDocuments_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Allotment", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Amenity", b =>
                {
                    b.Navigation("PropertyAmenities");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Application", b =>
                {
                    b.Navigation("Allotments");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Emiplan", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.HousingScheme", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Installment", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Loan", b =>
                {
                    b.Navigation("Emiplans");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Property", b =>
                {
                    b.Navigation("Allotments");

                    b.Navigation("Applications");

                    b.Navigation("PropertyAmenities");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HousingAllotmentManagementSystem.Models.User", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("AuditLogs");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("UserDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
