using HousingAllotmentManagementSystem.Data;
using HousingAllotmentManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HousingAllotmentManagementSystem.Controllers
{
    [Authorize]
    public class LoansController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LoansController(ApplicationDbContext context)
        {
            _context = context;
        }


        // =========================================================
        // INDEX
        // =========================================================

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var loans = await _context.Loans
                .Include(l => l.Allotment)
                    .ThenInclude(a => a.Application)
                        .ThenInclude(app => app.User)

                .Include(l => l.Allotment)
                    .ThenInclude(a => a.Property)
                        .ThenInclude(p => p.Scheme)

                .Include(l => l.Emiplans)

                .OrderByDescending(l => l.LoanId)
                .AsNoTracking()
                .ToListAsync();

            return View(loans);
        }


        // =========================================================
        // DETAILS
        // =========================================================

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loan = await _context.Loans
                .Include(l => l.Allotment)
                    .ThenInclude(a => a.Application)
                .Include(l => l.Emiplans)
                    .ThenInclude(e => e.Installments)
                .FirstOrDefaultAsync(l => l.LoanId == id);

            if (loan == null)
            {
                return NotFound();
            }

            return View(loan);
        }


        // =========================================================
        // CREATE - GET
        // =========================================================

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.AllotmentId = new SelectList(
                _context.Allotments
                    .OrderByDescending(a => a.CreatedDate)
                    .ToList(),
                "AllotmentId",
                "AllotmentNumber"
            );

            var loan = new Loan
            {
                SanctionDate = DateOnly.FromDateTime(DateTime.Today),
                LoanStatus = "Pending",
                CreatedDate = DateTime.Now
            };

            return View(loan);
        }


        // =========================================================
        // CREATE - POST
        // =========================================================

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Loan loan)
        {
            // Remove fields that are normally generated by the system
            ModelState.Remove(nameof(Loan.LoanId));
            ModelState.Remove(nameof(Loan.CreatedDate));

            // Check allotment
            var allotment = await _context.Allotments
                .FirstOrDefaultAsync(a =>
                    a.AllotmentId == loan.AllotmentId);

            if (allotment == null)
            {
                ModelState.AddModelError(
                    nameof(Loan.AllotmentId),
                    "Please select a valid allotment."
                );
            }


            // Check duplicate loan number
            if (!string.IsNullOrWhiteSpace(loan.LoanNumber))
            {
                var duplicateLoanNumber = await _context.Loans
                    .AnyAsync(l =>
                        l.LoanNumber == loan.LoanNumber);

                if (duplicateLoanNumber)
                {
                    ModelState.AddModelError(
                        nameof(Loan.LoanNumber),
                        "This loan number already exists."
                    );
                }
            }


            // Check whether allotment already has a loan
            if (allotment != null)
            {
                var existingLoan = await _context.Loans
                    .AnyAsync(l =>
                        l.AllotmentId == loan.AllotmentId);

                if (existingLoan)
                {
                    ModelState.AddModelError(
                        nameof(Loan.AllotmentId),
                        "A loan already exists for this allotment."
                    );
                }
            }


            // Validate loan amount
            if (loan.LoanAmount <= 0)
            {
                ModelState.AddModelError(
                    nameof(Loan.LoanAmount),
                    "Loan amount must be greater than zero."
                );
            }


            // Validate down payment
            if (loan.DownPayment < 0)
            {
                ModelState.AddModelError(
                    nameof(Loan.DownPayment),
                    "Down payment cannot be negative."
                );
            }


            // Validate relationship between loan amount and down payment
            if (loan.LoanAmount > 0 &&
                loan.DownPayment >= loan.LoanAmount)
            {
                ModelState.AddModelError(
                    nameof(Loan.DownPayment),
                    "Down payment must be less than the loan amount."
                );
            }


            // Validate interest rate
            if (loan.InterestRate < 0)
            {
                ModelState.AddModelError(
                    nameof(Loan.InterestRate),
                    "Interest rate cannot be negative."
                );
            }


            // Validate tenure
            if (loan.LoanTenure <= 0)
            {
                ModelState.AddModelError(
                    nameof(Loan.LoanTenure),
                    "Loan tenure must be greater than zero."
                );
            }


            // Validate EMI
            if (loan.Emiamount < 0)
            {
                ModelState.AddModelError(
                    nameof(Loan.Emiamount),
                    "EMI amount cannot be negative."
                );
            }


            if (!ModelState.IsValid)
            {
                LoadAllotmentDropdown(loan.AllotmentId);
                return View(loan);
            }


            loan.CreatedDate = DateTime.Now;

            _context.Loans.Add(loan);

            await _context.SaveChangesAsync();

            TempData["Success"] =
                "Loan created successfully.";

            return RedirectToAction(nameof(Index));
        }


        // =========================================================
        // EDIT - GET
        // =========================================================

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loan = await _context.Loans
                .FirstOrDefaultAsync(l => l.LoanId == id);

            if (loan == null)
            {
                return NotFound();
            }

            LoadAllotmentDropdown(loan.AllotmentId);

            return View(loan);
        }


        // =========================================================
        // EDIT - POST
        // =========================================================

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            int id,
            Loan loan)
        {
            if (id != loan.LoanId)
            {
                return NotFound();
            }

            // Don't let form data modify CreatedDate
            ModelState.Remove(nameof(Loan.CreatedDate));

            // Check allotment
            var allotment = await _context.Allotments
                .FirstOrDefaultAsync(a =>
                    a.AllotmentId == loan.AllotmentId);

            if (allotment == null)
            {
                ModelState.AddModelError(
                    nameof(Loan.AllotmentId),
                    "Please select a valid allotment."
                );
            }


            // Check duplicate loan number
            if (!string.IsNullOrWhiteSpace(loan.LoanNumber))
            {
                var duplicateLoanNumber = await _context.Loans
                    .AnyAsync(l =>
                        l.LoanNumber == loan.LoanNumber &&
                        l.LoanId != loan.LoanId);

                if (duplicateLoanNumber)
                {
                    ModelState.AddModelError(
                        nameof(Loan.LoanNumber),
                        "This loan number already exists."
                    );
                }
            }


            // Check if another loan already uses this allotment
            var allotmentUsedByAnotherLoan = await _context.Loans
                .AnyAsync(l =>
                    l.AllotmentId == loan.AllotmentId &&
                    l.LoanId != loan.LoanId);

            if (allotmentUsedByAnotherLoan)
            {
                ModelState.AddModelError(
                    nameof(Loan.AllotmentId),
                    "Another loan already uses this allotment."
                );
            }


            // Validate loan amount
            if (loan.LoanAmount <= 0)
            {
                ModelState.AddModelError(
                    nameof(Loan.LoanAmount),
                    "Loan amount must be greater than zero."
                );
            }


            // Validate down payment
            if (loan.DownPayment < 0)
            {
                ModelState.AddModelError(
                    nameof(Loan.DownPayment),
                    "Down payment cannot be negative."
                );
            }


            if (loan.LoanAmount > 0 &&
                loan.DownPayment >= loan.LoanAmount)
            {
                ModelState.AddModelError(
                    nameof(Loan.DownPayment),
                    "Down payment must be less than the loan amount."
                );
            }


            // Validate interest
            if (loan.InterestRate < 0)
            {
                ModelState.AddModelError(
                    nameof(Loan.InterestRate),
                    "Interest rate cannot be negative."
                );
            }


            // Validate tenure
            if (loan.LoanTenure <= 0)
            {
                ModelState.AddModelError(
                    nameof(Loan.LoanTenure),
                    "Loan tenure must be greater than zero."
                );
            }


            if (!ModelState.IsValid)
            {
                LoadAllotmentDropdown(loan.AllotmentId);
                return View(loan);
            }


            try
            {
                var existingLoan = await _context.Loans
                    .FirstOrDefaultAsync(l =>
                        l.LoanId == loan.LoanId);

                if (existingLoan == null)
                {
                    return NotFound();
                }

                existingLoan.AllotmentId = loan.AllotmentId;
                existingLoan.LoanNumber = loan.LoanNumber;
                existingLoan.LoanAmount = loan.LoanAmount;
                existingLoan.DownPayment = loan.DownPayment;
                existingLoan.InterestRate = loan.InterestRate;
                existingLoan.LoanTenure = loan.LoanTenure;
                existingLoan.Emiamount = loan.Emiamount;
                existingLoan.SanctionDate = loan.SanctionDate;
                existingLoan.LoanStatus = loan.LoanStatus;

                await _context.SaveChangesAsync();

                TempData["Success"] =
                    "Loan updated successfully.";

                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LoanExists(loan.LoanId))
                {
                    return NotFound();
                }

                throw;
            }
        }


        // =========================================================
        // DELETE - GET
        // =========================================================

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loan = await _context.Loans
                .Include(l => l.Allotment)
                .Include(l => l.Emiplans)
                .FirstOrDefaultAsync(l =>
                    l.LoanId == id);

            if (loan == null)
            {
                return NotFound();
            }

            return View(loan);
        }


        // =========================================================
        // DELETE - POST
        // =========================================================

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var loan = await _context.Loans
                .Include(l => l.Emiplans)
                    .ThenInclude(e => e.Installments)
                .FirstOrDefaultAsync(l =>
                    l.LoanId == id);

            if (loan == null)
            {
                return NotFound();
            }


            // Delete related installments and EMI plans first
            foreach (var emiPlan in loan.Emiplans)
            {
                if (emiPlan.Installments != null &&
                    emiPlan.Installments.Any())
                {
                    _context.Installments.RemoveRange(
                        emiPlan.Installments);
                }
            }

            if (loan.Emiplans != null &&
                loan.Emiplans.Any())
            {
                _context.Emiplans.RemoveRange(
                    loan.Emiplans);
            }


            _context.Loans.Remove(loan);

            await _context.SaveChangesAsync();

            TempData["Success"] =
                "Loan deleted successfully.";

            return RedirectToAction(nameof(Index));
        }


        // =========================================================
        // HELPERS
        // =========================================================

        private void LoadAllotmentDropdown(int? selectedId = null)
        {
            ViewBag.AllotmentId = new SelectList(
                _context.Allotments
                    .OrderBy(a => a.AllotmentNumber)
                    .ToList(),
                "AllotmentId",
                "AllotmentNumber",
                selectedId
            );
        }


        private bool LoanExists(int id)
        {
            return _context.Loans
                .Any(e => e.LoanId == id);
        }
    }
}